### ISSUE TITLE
TH and AoFS do not combine properly

### ISSUE THREAD

**Issue by L-Lawless** [konstmonst/matchless_kungfu_combo_creator#1]
TH (NAOOAN) and AoFS (ONAOOA) should ideally combine into ONAOOAN, but instead combine into ONAOOA.

**Comment by konstmonst** [comment]
Thanks for the bug, I'll check it out

**Comment by konstmonst** [comment]
It was off by one error, I added a test and fixed it

**Comment by konstmonst** [comment]
Well, closing this, since no complaints
